# Generated by Django 6.0.4 on 2026-04-23 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto')], default='CARRO', max_length=10)),
                ('modalidad', models.CharField(choices=[('DIA_HORA', 'Día/Hora'), ('MENSUALIDAD', 'Mensualidad')], default='DIA_HORA', max_length=20)),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('es_pago_mensualidad', models.BooleanField(default=False)),
                ('registra_solo_salida', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('total_pagar', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
