# Generated by Django 6.0.4 on 2026-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto')], default='CARRO', max_length=10),
        ),
    ]
