# Generated by Django 6.0.4 on 2026-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_activo_reserva_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
