# Generated by Django 6.0.4 on 2026-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_entrada']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='es_pago_mensualidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_pagar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
