# Generated by Django 6.0.4 on 2026-04-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_options_reserva_es_pago_mensualidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='registra_solo_salida',
            field=models.BooleanField(default=False),
        ),
    ]
