# Generated by Django 6.0.4 on 2026-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_registra_solo_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
